spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liontalk/SpringCloud_Config
          username:
          password:
          default-label: master
server:
  port: 8300